DROP TABLE IF EXISTS Persons;

CREATE TABLE Persons (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LastName TEXT NOT NULL,
    FirstName TEXT,
    MiddleName TEXT,
    Note TEXT,
    PersonalCaseDir TEXT
);

DROP TABLE IF EXISTS Files;

CREATE TABLE Files (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Type TEXT NOT NULL,
    FileName TEXT NOT NULL
);

DROP TABLE IF EXISTS Reports;

CREATE TABLE Reports (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name Text NOT NULL,
    Year INTEGER NOT NULL
);

DROP TABLE IF EXISTS ReportRegistry;

CREATE TABLE ReportRegistry (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FileID INTEGER,
    ReportID INTEGER,
    FOREIGN KEY (FileID) REFERENCES Files (ID)
    FOREIGN KEY (ReportID) REFERENCES Reports (ID)
);

DROP TABLE IF EXISTS PersonRegistry;

CREATE TABLE PersonRegistry (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PersonID INTEGER,
    FileID INTEGER,
    ReportID INTEGER,
    PersonalCase INTEGER,
    Page INTEGER,
    FOREIGN KEY (PersonID) REFERENCES Persons (ID)
    FOREIGN KEY (FileID) REFERENCES Files (ID)
    FOREIGN KEY (ReportID) REFERENCES Reports (ID)
);
